version: '3'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    volumes:
      - .:/app
    environment:
      PYGAME_HIDE_SUPPORT_PROMPT: 1

networks:
  default:
